### PR TITLE
Monkeypatch neo4j longer

### PR DESCRIPTION
**Pull request by pudiva**

### CODE REVIEW

**Review by Reyko — COMMENTED** [review]
Should we close the previous PR and just keep this one instead?

**Comment by pudiva** [comment]
> Should we close the previous PR and just keep this one instead?

I just did that PR to have review app on Heroku to test. Will close as soon as I'm done with it!

**Comment by pudiva** [comment]
added labels

**Comment by Reyko** [comment]
coolio

**Comment by pudiva** [comment]
closing in favour of #187

**Pull request closed without merging**
