### PR TITLE
Allow ruby 2.6

### PR DESCRIPTION
**Pull request by pudiva**

### CODE REVIEW

**Comment by pudiva** [comment]
This **don't change server's ruby**, only make the app not complain if your ruby version is newer than 2.5.3.

**Review by cdccollins — APPROVED** [review]

**Comment by spannerinworks** [comment]
pls check tests run under docker. changes seem to run tests on dev database rather than test one

**Comment by cdccollins** [comment]
Tried to run the tests in docker and they are all failing magnificently. 

```
 WebMock::NetConnectNotAllowedError:
         Real HTTP connections are disabled. Unregistered request: POST http://neo4j_db:7474/db/data/transaction/commit with body '{"statements":[{"statement":"MATCH (n) WHERE NOT n:`Neo4j::Migrations::SchemaMigration` DETACH DELETE n\n","parameters":{},"resultDataContents":["row","REST"]}]}' with headers {'Accept'=>'application/json; charset=UTF-8', 'Content-Type'=>'application/json', 'Expect'=>'', 'User-Agent'=>'neo4j-core-gem/8.1.4 (https://github.com/neo4jrb/neo4j-core)'}
```

**Comment by pudiva** [comment]
@cdccollins can you test it on docker again? it should work now.

**Comment by cdccollins** [comment]
@̶a̶y̶g̶h̶o̶r̶ ̶I̶ ̶p̶u̶l̶l̶e̶d̶ ̶i̶t̶ ̶a̶n̶d̶ ̶t̶h̶e̶ ̶t̶e̶s̶t̶s̶ ̶a̶r̶e̶ ̶s̶t̶i̶l̶l̶ ̶f̶a̶i̶l̶i̶n̶g̶.̶ ̶T̶r̶i̶e̶d̶ ̶r̶u̶n̶n̶i̶n̶g̶ ̶t̶h̶e̶m̶ ̶o̶n̶ ̶d̶e̶v̶e̶l̶o̶p̶ ̶a̶n̶d̶ ̶t̶h̶e̶y̶ ̶w̶o̶r̶k̶.̶ ̶

@ayghor my branch was ahead/behind or something, checked out the right commit and the tests pass 👍

**Comment by pudiva** [comment]
@cdccollins thank you!

**Pull request merged**
